### ISSUE TITLE
[Java-bug-1] Delete QuickSort code

### ISSUE THREAD

**Issue by AccaEmme** [AccaEmme/CARE#12]
Oltre a non essere adatto reimplementare un algoritmo presente nelle librerie, l'ordinamento avviene direttamente dal DB che restituisce i risultati mediante una query specifica definita come `SELECT...FROM...WHERE... ORDER BY...`
Credo sia il caso di eliminare la porzione di codice inerente all'ordinamento

**Comment by follen99** [comment]
Concordiamo insieme che l'implementazione del QuickStort non verrà aggiunta al sistema finale.

**Comment by follen99** [comment]
Concordiamo insieme che l'implementazione del QuickStort non verrà aggiunta al sistema finale.
